name: Development Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Development Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set version
      run: |
        GIT_COMMIT=$(git rev-parse --short HEAD)
        echo "VERSION=Dev-${GIT_COMMIT}" >> $GITHUB_ENV

    - name: Build and Package
      run: |
        make VERSION=${{ env.VERSION }} dmg

    - name: Verify Architecture Support
      run: |
        echo "Check development version architecture compatibility..."
        make check-arch

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Generate Changelog
      run: |
        gem install github_changelog_generator
        github_changelog_generator -u samzong -p ConfigForge --token ${{ secrets.GITHUB_TOKEN }} --unreleased-only
        cat CHANGELOG.md > release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Development Version"
        body_path: release_notes.md
        draft: false
        prerelease: true
        tag_name: "develop"
        files: |
          build/ConfigForge-x86_64.dmg
          build/ConfigForge-arm64.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 