name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Packages
        run: |
          make VERSION=${{ env.VERSION }} dmg

      - name: Verify Architecture Support
        run: |
          echo "==> Check release version architecture compatibility..."
          make check-arch

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Generate Changelog
        run: |
          gem install github_changelog_generator
          github_changelog_generator -u samzong -p ConfigForge --token ${{ secrets.GITHUB_TOKEN }} --future-release ${{ env.VERSION }}
          cat CHANGELOG.md > release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.VERSION }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            build/ConfigForge-x86_64.dmg
            build/ConfigForge-arm64.dmg
            CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Homebrew Update
        # 仅在发布成功时触发工作流
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: trigger-homebrew-update
          client-payload: '{"version": "${{ env.VERSION }}"}'

      - name: Update Latest Tag
        run: |
          git tag -f latest
          git push origin latest --force 